### ISSUE TITLE
ADDR нигде не используется

### ISSUE THREAD

**Issue by nikitaksv** [VladimirButakov/bxb_home#3]
https://github.com/VladimirButakov/bxb_home/blob/3e2dc419afb56a1805507c4f2bccea5b2a44e4f1/internal/server/http/server.go#L28

Переменная окружения нигде нн используется

**Comment by VladimirButakov** [comment]
log.Printf("handler is listening at %s", addr)

**Comment by nikitaksv** [comment]
У тебя лог с ней печатается да, но сервер запускается то не на этом адресе

**Comment by nikitaksv** [comment]
На 22 строку посмотри, там адрес :3000
